services:
  database:
    env_file:
      - back/.env
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: goose
      POSTGRES_PASSWORD: goosethebest
      POSTGRES_DB: web-project
    networks:
      - app-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build:
      context: ./back
    command: fastapi run
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-networks
  frontend:
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

networks:
  app-networks:

volumes:
  postgres_data:
