services:
  backend:
    build:
      context: ./back
    command: fastapi run
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

